variables:
  DOCKER_DRIVER: overlay2

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

maven-build-job:       # This job runs in the build stage, which runs first.
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar


deploy-job:      # This job runs in the deploy stage.
  image: docker:latest
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  services:
    - name: docker:dind
  script:
    - echo "Setting up Docker Buildx..."
    - docker buildx create --use
    - docker buildx ls
    - echo "Login..."
    - docker login -u gitlab-ci-token -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - echo "Deploying application..."
    - docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/vladkarandashov/cars-business-card:latest --push -f Dockerfile .
    - echo "Application successfully deployed."