spring:
  application:
    name: business-card-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BCS_DATABASE_URL}
    username: ${BCS_DATABASE_USERNAME}
    password: ${BCS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: ${BCS_DATABASE_SCHEMA}
    show_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
    contexts: local
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
  security:
    user:
      password: ${BCS_ADMIN_PASSWORD}
      name: admin
    cors:
      allowed-origins: ${BCS_CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    ru.abradox: DEBUG